language: bash
dist: bionic
before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker --version
  - docker buildx version
  - docker buildx create --name builder --driver docker-container --use
  - docker buildx inspect --bootstrap
  - docker buildx ls
  - export REPO=octoate/thingsboard-gateway-multiplatform
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi
  - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --tag $REPO:$COMMIT -f ./docker/Dockerfile .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
